Fix bug with Intel GPUs.
RVC-Project/Retrieval-based-Voice-Conversion pull request #47
Opened 2024-11-10 22:52 UTC by alcoftTAO

Fixes a bug occurring on Intel GPUs in the file *rvc/lib/infer_pack/models.py* when the `align_corners` parameter is set to **True**.

This fix dynamically sets `align_corners` to **False** when the model is loaded on an **xpu** device and **True** otherwise.

2024-11-28 15:45 UTC, fumiama commented
This lib is not actively developing. If possible, please check https://github.com/fumiama/Retrieval-based-Voice-Conversion-WebUI and test whether it works on your platform.

2025-07-13 14:33 UTC, Tps-F requested changes
Can you just undo change in .gitignore?
I'll merge it

2025-07-13 14:33 UTC, Tps-F commented on .gitignore
> +input.wav
Please undo this change because those files are not included in this project.

2025-07-13 15:32 UTC, Tps-F approved these changes

2025-07-13 15:32 UTC, merged

2025-07-13 15:32 UTC, Tps-F commented
Thank you for your work!